name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest

        #- name: macOS
        #  os: macos-latest

        #- name: Android32
        #  os: ubuntu-latest
        #  target: Android32

        #- name: Android64
        #  os: ubuntu-latest
        #  target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: List PersistenceAPI workflows
        id: list-workflows
        run: |
          echo "PA_WORKFLOWS=$(curl.exe -L `
          -H 'Accept: application/vnd.github+json; charset=utf-8' `
          'https://api.github.com/repos/0x5abe/PersistenceAPI/actions/runs?per_page=1&status=success')" `
          >> $GITHUB_OUTPUT

      - name: test workflow id
        run: |
          echo " Workflow id: " $ID
        env:
          ID: ${{ fromjson(steps.list-workflows.outputs.PA_WORKFLOWS).workflow_runs[0].id }}
  
      #- name: Fetch PersistenceAPI
      #  uses: actions/download-artifact@v4
      #  with:
      #    repository: 0x5abe/PersistenceAPI
      #    run-id: ${{ fromjson(steps.list-workflows.outputs.PA_WORKFLOWS).workflow_runs[0].id }}

      #- name: Build the mod
      #  uses: geode-sdk/build-geode-mod@main
      #  with:
      #    bindings: 0x5abe/geode-bindings
      #    bindings-ref: main
      #    combine: true
      #    target: ${{ matrix.config.target }}

  #package:
  #  name: Package builds
  #  runs-on: ubuntu-latest
  #  needs: ['build']

  #  steps:
  #    - uses: geode-sdk/build-geode-mod/combine@main
  #      id: build
  #
  #    - uses: actions/upload-artifact@v4
  #      with:
  #        name: Build Output
  #        path: ${{ steps.build.outputs.build-output }}
